package org.titiplex.persistence.repo;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;
import org.titiplex.persistence.model.ScenarioTemplate;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

@Repository
public class ScenarioTemplateRepository {

    private final JdbcTemplate jdbcTemplate;

    public ScenarioTemplateRepository(@Qualifier("templatesJdbcTemplate") JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS scenario_template (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    source_scenario_id BIGINT NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    description CLOB,
                    language_id VARCHAR(20) NOT NULL,
                    source_author VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP NOT NULL
                )
                """);
    }

    public ScenarioTemplate save(Long sourceScenarioId, String title, String description, String languageId, String sourceAuthor) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        Instant now = Instant.now();

        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(
                    """
                    INSERT INTO scenario_template (source_scenario_id, title, description, language_id, source_author, created_at)
                    VALUES (?, ?, ?, ?, ?, ?)
                    """,
                    Statement.RETURN_GENERATED_KEYS
            );
            ps.setLong(1, sourceScenarioId);
            ps.setString(2, title);
            ps.setString(3, description);
            ps.setString(4, languageId);
            ps.setString(5, sourceAuthor);
            ps.setTimestamp(6, Timestamp.from(now));
            return ps;
        }, keyHolder);

        Number key = keyHolder.getKey();
        if (key == null) {
            throw new IllegalStateException("Template ID generation failed");
        }

        return new ScenarioTemplate(key.longValue(), sourceScenarioId, title, description, languageId, sourceAuthor, now);
    }

    public Optional<ScenarioTemplate> findById(Long id) {
        try {
            return Optional.ofNullable(jdbcTemplate.queryForObject(
                    """
                    SELECT id, source_scenario_id, title, description, language_id, source_author, created_at
                    FROM scenario_template
                    WHERE id = ?
                    """,
                    (rs, rowNum) -> new ScenarioTemplate(
                            rs.getLong("id"),
                            rs.getLong("source_scenario_id"),
                            rs.getString("title"),
                            rs.getString("description"),
                            rs.getString("language_id"),
                            rs.getString("source_author"),
                            rs.getTimestamp("created_at").toInstant()
                    ),
                    id
            ));
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    public List<ScenarioTemplate> findAll(String languageId) {
        if (languageId == null || languageId.isBlank()) {
            return jdbcTemplate.query(
                    """
                    SELECT id, source_scenario_id, title, description, language_id, source_author, created_at
                    FROM scenario_template
                    ORDER BY created_at DESC
                    """,
                    (rs, rowNum) -> new ScenarioTemplate(
                            rs.getLong("id"),
                            rs.getLong("source_scenario_id"),
                            rs.getString("title"),
                            rs.getString("description"),
                            rs.getString("language_id"),
                            rs.getString("source_author"),
                            rs.getTimestamp("created_at").toInstant()
                    )
            );
        }

        return jdbcTemplate.query(
                """
                SELECT id, source_scenario_id, title, description, language_id, source_author, created_at
                FROM scenario_template
                WHERE language_id = ?
                ORDER BY created_at DESC
                """,
                (rs, rowNum) -> new ScenarioTemplate(
                        rs.getLong("id"),
                        rs.getLong("source_scenario_id"),
                        rs.getString("title"),
                        rs.getString("description"),
                        rs.getString("language_id"),
                        rs.getString("source_author"),
                        rs.getTimestamp("created_at").toInstant()
                ),
                languageId
        );
    }
}
