package org.titiplex.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.springdoc.core.customizers.OperationCustomizer;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.titiplex.api.security.OpenApiAccessCustomizer;
import org.titiplex.api.security.OwnerOrAdminOpenApiCustomizer;

@Configuration
public class OpenApiConfig {
    @Bean
    OpenAPI titiplexOpenAPI() {
        String bearerScheme = "bearerAuth";

        return new OpenAPI()
                .info(new Info()
                        .title("Vignette API")
                        .summary("Automated REST OpenAPI documentation for Vignette")
                        .description("""
                                This API is automatically generated by SpringDoc and is used to document the endpoints of the Vignette Java application.
                                It was originally created by Titouan Johanny, under the supervision of teacher <a href='mailto:louis.edouard.lafontant@umontreal.ca'>Louis-Edouard Lafontant</a>.
                                
                                Authentication model:
                                  - Public endpoints do not require authentication
                                  - Protected endpoints require a Bearer JWT
                                  - Browser-based flows may also rely on session cookies and CSRF
                                
                                Recommended integration mode for API clients:
                                  - use Authorization: Bearer <token>
                                """)
                        .termsOfService("https://github.com/Titiplex/vignette")
                        .version("1.0 (BETA)")
                        .contact(new Contact()
                                .name("Titouan Johanny")
                                .email("johannytitouan@gmail.com")
                                .url("https://github.com/Titiplex")
                        )
                        .license(new License()
                                .name("GNU")
                                .url("https://www.gnu.org/licenses/gpl-3.0.en.html")
                        )
                )
                .addServersItem(new Server()
                        .url("http://localhost:8081")
                        .description("Local development server"))
                .components(new Components()
                        .addSecuritySchemes(bearerScheme,
                                new SecurityScheme()
                                        .name("Authorization")
                                        .type(SecurityScheme.Type.HTTP)
                                        .scheme("bearer")
                                        .bearerFormat("JWT")
                                        .description("""
                                                JWT Bearer authentication.
                                                
                                                How to obtain a token:
                                                  - Call POST /api/auth/login with username and password
                                                  - Copy the token from the response body
                                                
                                                How to use it:
                                                  - Send header: Authorization: Bearer <token>
                                                
                                                Notes:
                                                  - Tokens currently expire after 1 hour
                                                  - Roles are stored in the JWT 'roles' claim
                                                """)));
    }

    @Bean
    GroupedOpenApi publicApi() {
        return GroupedOpenApi.builder()
                .group("public")
                .pathsToMatch("/api/**")
                .build();
    }

    @Bean
    OperationCustomizer accessCustomizer() {
        return new OpenApiAccessCustomizer();
    }

    @Bean
    OperationCustomizer ownerOrAdminCustomizer() {
        return new OwnerOrAdminOpenApiCustomizer();
    }
}
